### ISSUE TITLE
Anker Solix 2 E1600

### ISSUE THREAD

**Issue by BigMike71** [ioBroker/AdapterRequests#952] opened 2024-07-24 14:58 UTC
**What kind of device or service would you like to see an adapter for?**
https://www.anker.com/eu-de/products/a17c13z1?search_category=autofill&q=solarbank&o_1=1&o_2=1&o_2_p=1&o_3=2&o_3_v=1&o_4=1

**Is the device connected to the internet or only available on a local network?**
Cloud connected

**Is an official App or Website available?**
https://play.google.com/store/search?q=anker+app&c=apps&gl=DE

**Is an official API including documentation available?**
i think so

**Are other libraries for an integration available?**
https://github.com/thomluther/anker-solix-api

**Is this device already integrated in other Smart Home systems?**
https://github.com/thomluther/hacs-anker-solix

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
no

**Comment by mcm1957** [comment] 2024-07-24 15:00
duplicate of #855

**Closed by mcm1957** 2024-07-24 15:00 UTC
Labels: duplicate
