### ISSUE TITLE
Anker SOLIX Solarbank 2 E1600 Pro

### ISSUE THREAD

**Issue by Zephyr750** [ioBroker/AdapterRequests#957] opened 2024-08-02 08:00 UTC
**What kind of device or service would you like to see an adapter for?**
[Add name and company of the device, including links to the device and any additional information[...]]
(https://www.anker.com/eu-de/anker-solix/balkonkraftwerk-mit-speicher/solarbank2-a17c1-bms)

**Is the device connected to the internet or only available on a local network?**
Connected to the internet

**Is an official App or Website available?**
The App Anker Version 2.8.0

**Is an official API including documentation available?**
I don't know

**Are other libraries for an integration available?**
I don't know

**Is this device already integrated in other Smart Home systems?**
I don't know

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
I don't know

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mcm1957** [comment] 2024-08-02 09:08
duplicate of https://github.com/ioBroker/AdapterRequests/issues/855

**Closed** 2024-08-02 09:10 UTC
Labels: duplicate
