### ISSUE TITLE
Hue-Sync-Box Adapter

### ISSUE THREAD

**Issue by itwegner72** [ioBroker/AdapterRequests#360] opened 2020-03-03 17:43 UTC
Please create a Adapter for the Hue-Sync-Box to control it. The Api is avaible. THX.	

> *created by ioBroker.info*

**Comment by Apollon77** [comment] 2020-03-03 21:57
More details please!

**Comment by foxriver76** [comment] 2020-03-16 09:02
Duplicate of https://github.com/ioBroker/AdapterRequests/issues/324

**Closed by foxriver76** 2020-03-16 09:02 UTC
