### ISSUE TITLE
Bosch Indego Connect Adapter

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#63] opened 2018-05-07 17:15 UTC
https://forum.iobroker.net/viewtopic.php?t=10516

https://github.com/zazaz-de/iot-device-bosch-indego-controller

s. Openhab
https://docs.openhab.org/addons/bindings/boschindego/readme.html

![grafik](https://user-images.githubusercontent.com/39061622/39714628-f8050adc-522a-11e8-98e0-7870967d4412.png)

**Comment by Apollon77** [comment] 2018-06-17 20:17
Homebridge modules exist: homebridge-boschindego as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by TmShaz** [comment] 2018-09-05 16:42
Anyone working on this topic? I'am to stupid for this, but would like to have such an adapter.

**Comment by oldi2000** [comment] 2019-07-05 19:10
Hello
iobroker.ham adapter works, but the homebridge boschindego module is at most alpha stadium, objects are created but it can not more than start or stop the mower, no battery level, no progress  nothing.
I think it would be great if someone with a clue could look at the code from zazaz and could build a decent adapter, 
I can not do it unfortunately.

maybe this web adapter will help:
http://grauonline.de/alexwww/indego/indego.html
this works too

**Comment by a1development** [comment] 2020-06-30 06:54
Hi all, i created a Bosch Indego Adapter last weekend. Currently i am testing. But it looks stable. Once everything is polished, i will release it and let you know.

**Comment by TmShaz** [comment] 2020-06-30 07:14
This sounds great. Willing to test your adapter as soon as possible.

**Comment by SchiFrank** [comment] 2020-09-11 08:25
Any progress in this issued?

**Comment by a1development** [comment] 2020-09-11 12:17
I had some problems the the password encryption of ioBroker and differences between Version 2.x and 3.x of ioBroker. Otherwise this is working. I hope i will find some time soon to dig into this. Sorry for the delay.

**Comment by Apollon77** [comment] 2020-09-11 22:12
> I had some problems the the password encryption of ioBroker and differences between Version 2.x and 3.x of ioBroker.

WHat exactly you have as problem?

**Comment by Compacty87** [comment] 2020-12-18 07:46
Hello! Did you finish the Adapter ?

**Comment by Bernd1984** [comment] 2020-12-28 18:22
Any Updates for this topic? Thanks

**Comment by domstick** [comment] 2021-02-05 19:00
> Hi all, i created a Bosch Indego Adapter last weekend. Currently i am testing. But it looks stable. Once everything is polished, i will release it and let you know.

Hi, any news on your adapter? I could help testing it. I have the M700+ Hardware.

**Comment by a1development** [comment] 2021-03-20 16:17
OK. For Beta testing, i made the adapter public on github. 
https://github.com/a1development/ioBroker.boschindego
If you like you can give it a try. The UI of the Admin page is pretty basic for now. Just enter your credentials that you use in the indego app. 
Greetings Markus

**Comment by domstick** [comment] 2021-03-20 19:41
> OK. For Beta testing, i made the adapter public on github.
> https://github.com/a1development/ioBroker.boschindego
> If you like you can give it a try. The UI of the Admin page is pretty basic for now. Just enter your credentials that you use in the indego app.
> Greetings Markus

Thanks Markus!
Works like a charm so far. I'm happy to test it out!

**Comment by domstick** [comment] 2021-03-23 19:16
I did some testing and it's working great so far!
Buttons are working as intended and the state items are updating correctly within the limitations of Indego itself.
For my M700+ it's stable and I haven't encountered any issue or bug so far.

One of my favourites is the SVG-Code of the map in ioBroker. You can use that in a visualization easily and have a map of your lawn with Indegos position in it. 
Thank you very much, Markus! It was the last piece missing to make my garden fully smart.
Rain -> go home! Irrigation active -> go home! Not enough sunshine to dry out the lawn in the morning -> start later. Tun on Irrigation during Indegos charging process. Endless possibilities. I'm very happy!

There is no indicator for battery charge in percent, but thats a limitation of Bosch itself AFAIK.
But thera are workarounds within ioBroker itself. Your adapter shows start and end of charging via stateText. I'm logging that varible using InfluxDB, so I know how long a full charge lasts and when the charge started, so i can calculate a good guess. 

More of a feature request:
Could you eventually add error message texts? I had an error during testing today. Indego went to the station for a charge, but couldn't dock successfully. It stopped with the error message that he's been lifted (GER: "Indego wurde angehoben, bitte..").
In the stateText it was logged as "Idle in lawn." (see picture below).
![image](https://user-images.githubusercontent.com/39016069/112204253-bee6dc00-8c13-11eb-96f3-bf931211356d.png)
It would be great to have the error message text sent by Indego as an sate in ioBroker e.g. errorMessage.
One could then use it as a push-message, telegram message or make Alexa read it out loud.
It seems to be possible here: http://grauonline.de/alexwww/indego/indego.html

**Comment by DutchmanNL** [comment] 2021-03-23 20:11
So time to release a Beta Version, close this issue and continue in te Adapter repo? 😉

**Comment by a1development** [comment] 2021-03-23 21:08
@domstick thank you for your feedback and the time to test things out. 
From the API i get the state, wich is a number. You can find it under state.state in the adapter. 
Then i try to match the number against a list of known states. If it is found, the stateText is updated. 

It would be very interesting to have the state during the changes. I guess the state was not known and the stateText did show the last known state. 
Idle in lawn is state 519

**Comment by domstick** [comment] 2021-03-23 22:40
> It would be very interesting to have the state during the changes. I guess the state was not known and the stateText did show the last known state.
> Idle in lawn is state 519

I have to log the state number and provoke some errors. I just logged stateText unfortunately.
I'll do some testing on that.

Maybe Indego goes to "Idle in lawn" state and throws the error message seperately. Indego stops and stands still in error state so "Idle" would be the correct description ;)
I found a list of status codes here:
https://github.com/zazaz-de/iot-device-bosch-indego-controller/blob/master/PROTOCOL.md
It seems, that error messages are seperated in the API, if I'm reading it correctly.
`GET https://api.indego.iot.bosch-si.com/api/v1/alerts
x-im-context-id: {contextId}

Response:
[
  {
    "alm_sn": "1234567890",
    "alert_id": "12345678-abef-12de-3322-11aa22ee2387",
    "headline": "Wartungshinweis.",
    "date": "2016-05-14T16:29:31.123Z",
    "message": "Messer prüfen. Ihr Indego hat 100 Stunden gemäht. Prüfen Sie bitte die Messer auf einwandfreien Zustand, damit weiterhin die optimale Leistung gewährleistet ist. ",
    "read_status": "unread",
    "flag": "warning"
  },
  {
    "alm_sn": "1234567890",
    "alert_id": "12345678-abef-12de-3322-11aa22ee2387",
    "headline": "Mäher benötigt Hilfe.",
    "date": "2016-05-14T14:10:23.112Z",
    "message": "Begrenzungsdrahtsignal über längere Zeit nicht erkannt. Ihr Indego hat für einige Zeit das Begrenzungsdrahtsignal nicht erkannt. Bitte prüfen Sie die Anschlüsse der Ladestation und des Begrenzungsdrahts.",
    "read_status": "unread",
    "flag": "warning"
  }
]`

**Comment by a1development** [comment] 2021-03-24 09:43
@domstick I just updated the Adapter to 0.9.1 and changed it so it updates the stateText to '123 - state unknown', in addition it throws a warn message in the logs with this information. That way it should be easier to catch new introduced states. 
It would be crutial to know what the new state number stands for, so if this happens, the only way to find out would be a look at the app. 
In my adapter there are more status codes then in the list you provided. So we should be covered. 

It could be that "idle in lawn" is shown and a alert message goes out. I looked at alerts. I can retrieve them. I just need to brush up my ioBroker Adapter skills and find a way to write changing lists to the state database ... ;)

**Comment by domstick** [comment] 2021-03-24 19:39
@a1development thank you! I installed it and am now logging status codes. I'm going to test out some codes by provoking some error states tomorrow during day-time.

**Comment by a1development** [comment] 2021-03-25 12:50
OK minor update to 0.9.2.
The Background of the mapSVGwithIndego is now transparent. That way it should better in different VIS, and you could put a satelite image of your garden in the background and overlay the map ;)

**Comment by domstick** [comment] 2021-03-27 16:16
![Uploading image.png…]()

**Comment by a1development** [comment] 2021-03-27 17:17
@domstick UPS .. i pushed it to github... still working on that. So the data points will change. Didn t ment to be in this version.

**Comment by domstick** [comment] 2021-03-27 22:59
> @domstick UPS .. i pushed it to github... still working on that. So the data points will change. Didn t ment to be in this version.

Looks very promising!

**Comment by Diggi3** [comment] 2021-04-08 08:05
Hi,

I perform an automatic restart of my router at 4 o'clock in the night. After that, the adapter cannot connect anymore:

```
boschindego.0 | 2021-04-08 04:02:08.863 | info | (81512) Got terminate signal TERMINATE_YOURSELF
boschindego.0 | 2021-04-08 04:02:08.815 | info | (81512) Terminated (NO_ERROR): Connection error. Credentials wrong?
boschindego.0 | 2021-04-08 04:02:08.807 | error | (81512) connect error
boschindego.0 | 2021-04-08 04:01:51.716 | info | (81512) connect
boschindego.0 | 2021-04-08 04:01:51.698 | info | (81512) starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.boschindego, node: v12.22.0, js-controller: 3.2.16
```

**Comment by a1development** [comment] 2021-04-08 15:30
> I perform an automatic restart of my router at 4 o'clock in the night. After that, the adapter cannot connect anymore:
> If I then start the adapter manually, it runs again until the next reboot.

Yes. I will handly this differently in a feature update. I was testing on this today aswell. 
It should go yellow an go back to green when it reconnects. 
Also there are some service outtakes from bosch from time to time where this happens as well

**Comment by a1development** [comment] 2021-04-17 08:52
@Diggi3 OK i just updated the adapter to 0.9.4. 
In this release, the adapter will turn yellow if there are connection problems and tries to reconnect periodicaly -> turns green if reconnected. 
In this version  there is also the info.connection Object added.

**Comment by asch8505** [comment] 2021-04-19 10:10
> 
> 
> OK. For Beta testing, i made the adapter public on github.
> https://github.com/a1development/ioBroker.boschindego
> If you like you can give it a try. The UI of the Admin page is pretty basic for now. Just enter your credentials that you use in the indego app.
> Greetings Markus

Very nice, works like a charm, thank you very much for this adapter :) even the map can be easily integrated in vis. But I have a little question. I cannot find the current battery state, is it possible to get this information via API or is it the information not given by Bosch?

**Comment by a1development** [comment] 2021-04-19 10:21
@asch8505 The battery state is not given

**Comment by Diggi3** [comment] 2021-04-23 05:42
> Hi,
> 
> I perform an automatic restart of my router at 4 o'clock in the night. After that, the adapter cannot connect anymore:
> 
> ```
> boschindego.0 | 2021-04-08 04:02:08.863 | info | (81512) Got terminate signal TERMINATE_YOURSELF
> boschindego.0 | 2021-04-08 04:02:08.815 | info | (81512) Terminated (NO_ERROR): Connection error. Credentials wrong?
> boschindego.0 | 2021-04-08 04:02:08.807 | error | (81512) connect error
> boschindego.0 | 2021-04-08 04:01:51.716 | info | (81512) connect
> boschindego.0 | 2021-04-08 04:01:51.698 | info | (81512) starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.boschindego, node: v12.22.0, js-controller: 3.2.16
> ```
> 
> If I then start the adapter manually, it runs again until the next reboot.

Hi, 

thanks for your effort, worked much better now.
Unfortunately, the Indego is already defective after one year with a water damage.  Bosch service does not want to repair the device under warranty and charged for a repair more than the new price of the device. Therefore, I can unfortunately no longer test the adapter. And after the bad experience with the bosch service I will not buy an Indego again...

**Comment by Diggi3** [comment] 2021-04-23 05:42
> @Diggi3 OK i just updated the adapter to 0.9.4.
> In this release, the adapter will turn yellow if there are connection problems and tries to reconnect periodicaly -> turns green if reconnected.
> In this version there is also the info.connection Object added.

Hi, 

thanks for your effort, worked much better now.
Unfortunately, the Indego is already defective after one year with a water damage.  Bosch service does not want to repair the device under warranty and charged for a repair more than the new price of the device. Therefore, I can unfortunately no longer test the adapter. And after the bad experience with the bosch service I will not buy an Indego again...

**Comment by a1development** [comment] 2021-05-16 10:55
New Version 0.9.9 added "deep sleep mode" for bot connections during night time, so the bot will not be waken up to check the status.

**Comment by ldittmar81** [comment] 2022-01-06 07:49
@a1development Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories

**Comment by kubovy** [comment] 2022-01-06 12:33
Hi @a1development this adapter is a great addition!

Is the development still going on? I had some trouble to install it. Eventually I cloned it in the docker manually and after iobroker restart it started working.

**Comment by mcm1957** [comment] 2022-11-16 14:08
Adpater available at https://github.com/a1development/ioBroker.boschindego

@a1development 
Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories
 
Additional help is available via telegram too if required:
    https://t.me/+gsX-e8k4mLtmZjZk (iobroker adapter developer starters)
    https://t.me/ioBroker_development

I will mark this request as completed and close it in the near future

**Comment by mcm1957** [comment] 2024-03-16 18:43
Repo: https://github.com/iobroker-community-adapters/ioBroker.boschindego

Released to latest
Please create a issue at the adapter repository for any problems or feature requests.

**Closed by mcm1957** 2024-03-16 18:43 UTC
Labels: InProgress
