### ISSUE TITLE
FoxEss T10-G3

### ISSUE THREAD

**Issue by evschudo** [ioBroker/AdapterRequests#851] opened 2023-07-15 11:24 UTC
**What kind of device or service would you like to see an adapter for?**
FoxEss T10-G3  Wechselrichter für PV-Anlagen

**Is the device connected to the internet or only available on a local network?**
Internetverbindung über WLAN

**Is an official App or Website available?**
https://www.solarfy.de/FoxESS-T10-G3-10KW
https://github.com/assembly12/Foxess-T-series-ESPHome-Home-Assistant

**Is this device already integrated in other Smart Home systems?**
https://github.com/macxq/foxess-ha

**Comment by mcm1957** [comment] 2024-07-19 19:57
duplicate of https://github.com/ioBroker/AdapterRequests/issues/810

**Closed by mcm1957** 2024-07-19 19:57 UTC
Labels: duplicate
