### ISSUE TITLE
Support of windy.com as widget for vis and material

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/AdapterRequests#100] opened 2018-08-05 13:27 UTC
https://api4.windy.com/

**Comment by dwm66** [comment] 2018-08-31 08:51
Would be cool!

**Comment by GermanBluefox** [comment] 2018-08-31 10:14
You can make it with html iframe

пт, 31 авг. 2018 г., 10:51 dwm66 <notifications@github.com>:

**Comment by GermanBluefox** [comment] 2018-08-31 10:16
https://youtu.be/MwkLAvADDe8

пт, 31 авг. 2018 г., 12:14 Smart Home - ioBroker <dogafox@googlemail.com>:

**Comment by Apollon77** [comment] 2019-06-06 15:00
closing as duplicate of #215 (because this has no votes, the other has some)

**Closed by Apollon77** 2019-06-06 15:00 UTC
Labels: Requested
