### ISSUE TITLE
Adapter for Fox Ess Cloud kommunikation with Photovoltaik Plants

### ISSUE THREAD

**Issue by vosi2** [ioBroker/AdapterRequests#951] opened 2024-07-19 14:54 UTC
**What kind of device or service would you like to see an adapter for?**
I would connect a PV Plant from Fox ESS which is connectet to the FoxCloud with iobroker to sent/receive Operating Data. For those applikations Fox has a API for the Cloud.

**Is the device connected to the internet or only available on a local network?**
The PV Plant is connected with the internet.

**Is an official App or Website available?**
The App from Fox you can find under https://play.google.com/store/apps/details?id=com.fox.foxapp.two&hl=de&gl=US
The Webside for the Fox Ess Cloud can you finde her: https://www.foxesscloud.com/

**Is an official API including documentation available?**
The API docs you can finde her https://www.foxesscloud.com/public/i18n/en/OpenApiDocument.html

**Are other libraries for an integration available?**
I don´t know

**Is this device already integrated in other Smart Home systems?**
Not via Fox Cloud. It exsists connectors via Modbus direkt to the Inverter for older PV Inverters.

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
Its exsist a homebridge plugin https://github.com/macxq/foxess-ha. I will test it.

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mcm1957** [comment] 2024-07-19 19:58
duplicate of  https://github.com/ioBroker/AdapterRequests/issues/810

**Closed** 2024-07-19 19:59 UTC
Labels: duplicate
